#!/usr/bin/env perl
# Copyright (C) 2014 Tony Crisci <tony@dubstepdish.com>
# Copyright (C) 2015 Thiago Perrotta <perrotta dot thiago at poli dot ufrj dot br>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Requires playerctl binary to be in your path (except cmus)
# See: https://github.com/acrisci/playerctl

# Set instance=NAME in the i3blocks configuration to specify a music player
# (playerctl will attempt to connect to org.mpris.MediaPlayer2.[NAME] on your
# DBus session).

sub buttons {
    my $method = shift;
    if ($ENV{'BLOCK_BUTTON'} == 1) {
        print(`date '+%d/(%m|%b)/%Y'`);
    } elsif ($ENV{'BLOCK_BUTTON'} == 3) {
        print(`jdate +%G' '%d'/('%m'|'%V')/'%Y`);
    }
}
buttons();
print(`jdate +%G' '%d'/('%m'|'%V')/'%Y`);
print("\n");
